Add BungeeCord support
SpaceCodePoland/spaceis-plugin pull request #2
Opened 2023-01-20 19:07 UTC by P3ridot

2023-01-20 19:07 UTC, P3ridot commented
@Kamilkime

2023-02-03 20:25 UTC, Kamilkime requested changes

2023-02-03 20:25 UTC, Kamilkime commented on README.md
> +- Bukkit/Spigot/Paper/... - 1.8 do 1.19.3
No przecież dobrze było, co pan tu zmienia

2023-02-03 20:25 UTC, Kamilkime commented on bukkit/src/main/java/pl/spaceis/plugin/bukkit/BukkitSpaceIsCommand.java
>      private static final Set<String> RELOAD_ARGS = new HashSet<>(Arrays.asList("rl", "reload"));
Tu można w sumie oddzielić jeszcze pustą linią od pól obiektu

2023-02-03 20:25 UTC, Kamilkime commented on bukkit/src/main/java/pl/spaceis/plugin/bukkit/BukkitSpaceIsCommand.java
> +public class BukkitSpaceIsCommand implements CommandExecutor {
Skoro każda komenda robi to samo... Może by ją też jakoś zrobić abstrakcyjnie, żeby tylko się dostarczało implementacje np. hasPermission czy sendMessage

2023-02-03 20:25 UTC, Kamilkime commented on bukkit/src/main/java/pl/spaceis/plugin/bukkit/BukkitMessages.java
> +package pl.spaceis.plugin.bukkit;
Info o licencji jeszcze

2023-02-03 20:25 UTC, Kamilkime commented on bungee/src/main/java/pl/spaceis/plugin/bungee/BungeeCommandsTask.java
> +package pl.spaceis.plugin.bungee;
Info o licencji jeszcze

2023-02-03 20:25 UTC, Kamilkime commented on bungee/src/main/java/pl/spaceis/plugin/bungee/BungeeConfigLoader.java
> +package pl.spaceis.plugin.bungee;
Info o licencji jeszcze

2023-02-03 20:25 UTC, Kamilkime commented on bungee/src/main/java/pl/spaceis/plugin/bungee/BungeeMessages.java
> +        return new TextComponent(TextComponent.fromLegacyText(ChatColor.translateAlternateColorCodes('&', message)));
Kolorowanie można wydzielić do zmiennej dodatkowej, a dopiero z tego robić komponent - będzie lepiej widać o co chodzi

2023-02-03 20:25 UTC, Kamilkime commented on bungee/src/main/java/pl/spaceis/plugin/bungee/BungeeMessages.java
> +package pl.spaceis.plugin.bungee;
Info o licencji jeszcze

2023-02-03 20:25 UTC, Kamilkime commented on bungee/src/main/java/pl/spaceis/plugin/bungee/BungeeResourceLoader.java
> +package pl.spaceis.plugin.bungee;
Info o licencji jeszcze

2023-02-03 20:25 UTC, Kamilkime commented on bungee/src/main/java/pl/spaceis/plugin/bungee/BungeeResourceLoader.java
> +}
Pusta linia na koniec

2023-02-03 20:25 UTC, Kamilkime commented on bungee/src/main/java/pl/spaceis/plugin/bungee/BungeeSpaceIsCommand.java
> +    private static final Set<String> RELOAD_ARGS = new HashSet<>(Arrays.asList("rl", "reload"));
Oddzielić

2023-02-03 20:25 UTC, Kamilkime commented on bungee/src/main/java/pl/spaceis/plugin/bungee/BungeeSpaceIsCommand.java
> +package pl.spaceis.plugin.bungee;
Info o licencji jeszcze

2023-02-03 20:25 UTC, Kamilkime commented on bungee/src/main/java/pl/spaceis/plugin/bungee/BungeeSpaceIsLogger.java
> +package pl.spaceis.plugin.bungee;
Info o licencji jeszcze

2023-02-03 20:25 UTC, Kamilkime commented on bungee/src/main/java/pl/spaceis/plugin/bungee/BungeeSpaceIsPlugin.java
> +            final ConfigLoader configLoader = new BungeeConfigLoader(resourceLoader,"config.yml");
Spacja po przecinku

2023-02-03 20:25 UTC, Kamilkime commented on bungee/src/main/java/pl/spaceis/plugin/bungee/BungeeSpaceIsPlugin.java
> +package pl.spaceis.plugin.bungee;
Info o licencji jeszcze

2023-02-03 20:25 UTC, Kamilkime commented on common/src/main/java/pl/spaceis/plugin/config/Messages.java
> + * Copyright (C) 2023 Kamil Trysiński
Tu by trzeba zmienić na wszystkich contributorów już

2023-02-03 20:25 UTC, Kamilkime commented on common/src/main/java/pl/spaceis/plugin/config/ConfigLoader.java
> +    void reloadConfig() throws ResourceLoaderException;
No nie wiem w sumie, czy tak na pewno powinno być, bo ten reload nie musi mieć nic wspólnego z tym resource loaderem

2023-02-03 20:25 UTC, Kamilkime commented on common/src/main/java/pl/spaceis/plugin/resource/ResourceLoader.java
> +package pl.spaceis.plugin.resource;
Info o licencji jeszcze

2023-02-03 20:25 UTC, Kamilkime commented on common/src/main/java/pl/spaceis/plugin/resource/ResourceLoader.java
> +}
Pusta linia na koniec

2023-02-03 20:25 UTC, Kamilkime commented on common/src/main/java/pl/spaceis/plugin/resource/ResourceLoaderException.java
> +}
Pusta linia na koniec

2023-02-03 20:25 UTC, Kamilkime commented on common/src/main/java/pl/spaceis/plugin/resource/ResourceLoaderException.java
> +package pl.spaceis.plugin.resource;
Info o licencji jeszcze

2023-02-03 20:28 UTC, Kamilkime commented on README.md
>  Autor pluginu: [Kamilkime](https://github.com/Kamilkime)
I tu trzeba zmienić od razu na contributorów

2023-03-03 15:04 UTC, Kamilkime approved these changes

2023-03-03 15:05 UTC, merged